<?php

namespace AppBundle\Repository;

/**
 * PostTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostTagRepository extends \Doctrine\ORM\EntityRepository
{
}
